@startuml "techtribesjs"
'Build
!includeurl https://raw.githubusercontent.com/patternstormdf/c4model/master/c4plantuml/C4_Container.puml
'Local Dev
'!include ../c4plantuml/C4_Container.puml
!include Containers.puml


LAYOUT_TOP_DOWN
'LAYOUT_AS_SKETCH

hide stereotype

rectangle "Legend" {
    rectangle "External System" <<external_system>> as ext_sys
    rectangle "Container" <<container>> as cont
}

PipelineEventBus()
PipelineEventProcessor()
CICDEngine()
Rel_Back(PipelineEventBus,PipelineEventProcessor, "Publish Pipeline Execution Events", "JSON/HTTP")
Lay_D(PipelineEventProcessor,CICDEngine)
Rel(CICDEngine,PipelineEventProcessor, "Publish Pipeline Execution Events", "JSON/HTTP")
LogsDatastore()
Rel(CICDEngine,LogsDatastore,"Store Pipeline Execution Logs","FluentD")


@enduml
